---
- hosts: all
  become: true
  tasks:
    - name: install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: add docker repo
      command: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: makechache
      command: sudo yum makecache fast

    - name: install docker
      yum:
        name: docker-ce
        state: latest

    - name: start docker
      service:
        name: docker
        state: started

    - name: copy dockerfile templates
      copy:
        src: templates/
        dest: /opt/docker
        owner: root
        group: root
        mode: 0644
     
    - name: build docker image
      command: docker build -t vnginx . 
      args:
        chdir: /opt/docker

    - name: running microservice
      command: docker run -it -d -p 80:80 vnginx

